"""init

Revision ID: 1ebce9c0a10b
Revises:
Create Date: 2024-07-10 17:53:25.008645

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1ebce9c0a10b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_inputs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sentence", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "completion_configs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("top_k", sa.Integer(), nullable=False),
        sa.Column("top_p", sa.Float(), nullable=False),
        sa.Column("early_stopping", sa.Boolean(), nullable=False),
        sa.Column("num_return_sequences", sa.Integer(), nullable=False),
        sa.Column("num_beams", sa.Integer(), nullable=False),
        sa.Column("no_repeat_ngram_size", sa.Integer(), nullable=False),
        sa.Column("max_new_tokens", sa.Integer(), nullable=False),
        sa.Column("user_input_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_input_id"],
            ["user_inputs.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "completions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "completions", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("user_input_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_input_id"],
            ["user_inputs.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("completions")
    op.drop_table("completion_configs")
    op.drop_table("user_inputs")
    # ### end Alembic commands ###
